### ISSUE TITLE
[!] (plugin alias) TypeError: Cannot read property 'input' of undefined

### ISSUE THREAD

**Issue by shaoahs** [rollup/plugins#416] opened 2020-05-26 01:20 UTC
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 8.0.0
- Rollup Version: 2.10.9
- Operating System (or Browser): linux mageia 7.1
- Node Version: v12.16.1

### How Do We Reproduce?
if also use @rollup/plugin-alias
https://repl.it/repls/FrailSilverPoints#rollup.config.js

if modify 
https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/index.js

line 125
```
      const input = normalizeInput(rollupOptions.input);
```
to 
```
        if(!rollupOptions || !rollupOptions.input) {
          rollupOptions = {
            input: importee
          };
        }

        const input = normalizeInput(rollupOptions.input);
```
then it is normal !
is it okay for other plugins ?

### Expected Behavior

```
> npm run build

src/demo/main.js → public/bundle.js...
created public/bundle.js in 2.2s
```

### Actual Behavior

```
> npm run build

[!] (plugin alias) TypeError: Cannot read property 'input' of undefined
TypeError: Cannot read property 'input' of undefined
    at node_modules/@rollup/plugin-node-resolve/dist/index.js:509:52
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (node_modules/@rollup/plugin-node-resolve/dist/index.js:20:24)
    at _next (node_modules/@rollup/plugin-node-resolve/dist/index.js:42:9)
    at node_modules/@rollup/plugin-node-resolve/dist/index.js:49:7
    at new Promise (<anonymous>)
    at node_modules/@rollup/plugin-node-resolve/dist/index.js:38:12
    at resolveId (node_modules/@rollup/plugin-node-resolve/dist/index.js:642:9)
    at Object.resolveId (/node_modules/@rollup/plugin-alias/dist/index.js:79:24)
    at node_modules/rollup/dist/shared/rollup.js:18285:25
```

**Comment by shellscape** [comment] 2020-05-26 01:26
Can you add a minimal example of this error happening without any other plugins using one of the REPLs?

**Comment by shaoahs** [comment] 2020-05-26 03:01
if only use @rollup/plugin-node-resolve , it is okay !

need use three plugins ! (minimal)
```
import alias from '@rollup/plugin-alias';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
```

**Comment by shaoahs** [comment] 2020-05-26 03:31
is it this ?
https://repl.it/repls/FrailSilverPoints#rollup.config.js

**Comment by colesico** [comment] 2020-05-28 11:23
The same problem, pls fix. 
Can't use resolve with alias plugin.

**Comment by shellscape** [comment] 2020-05-28 11:26
_Please do not post "me too" type replies. Instead, use the reaction buttons. If you need an issue fixed immediately, please consider contributing a fix._

**Comment by shaoahs** [comment] 2020-05-29 00:48
### current status (use the same config)

I am not sure ! 
 need  modify plugin  "@rollup/plugin-alias"
or   "@plugin-node-resolve"
in last version


#### option 1 

it is work !

```
  "@rollup/plugin-alias": "^3.1.0",
  "@rollup/plugin-node-resolve": "~7.0.0"
```

#### option 2

 error !

```
  "@rollup/plugin-alias": "^3.1.0",
  "@rollup/plugin-node-resolve": "~8.0.0"
```
#### config

```
// rollup.config.js
import alias from '@rollup/plugin-alias';
import resolve from '@rollup/plugin-node-resolve';

const customResolver = resolve({
  extensions: ['.ts', '.mjs', '.js', '.yml', '.json', '.css']
});

let aliasConfig = {
  customResolver,
  entries: {
    'update': path.resolve('src/demo/update.js'),
    'src': path.resolve('src/demo/')
  }
};

export default {
  // ...
  plugins: [
    alias(aliasConfig),
    resolve()
  ]
};
```

**Comment by shellscape** [comment] 2020-05-29 15:02
Thanks for the reproduction. This is a duplicate of #203

**Closed by shellscape** 2020-05-29 15:02 UTC
