### ISSUE TITLE
The command will hang up and mot exit

### ISSUE THREAD

**Issue by franck-lynn** [rollup/plugins#991] opened 2021-09-03 05:44 UTC
- Rollup Plugin Name:  typescript
- Rollup Plugin Version: 8.2.5
- Rollup Version: 2.56.3
- Operating System (or Browser):  win10
- Node Version: 16.8.0

### Expected Behavior
Once configurate @rollup/plugin-typescript, and  run 

> nmp run start

package.json
```json{
     "start": "rollup --config rollup.config.js"
}
```
and the process will hang up, the comman will not exit.

> src/index.ts → dist/vue-rollup-component-template.esm.js...
> created dist/vue-rollup-component-template.esm.js in 5.8s

it will press down  ctrl + c , and the command quit.

> Terminate batch job (Y/N)?
> ^C
> PS F:

**Comment by htho** [comment] 2021-09-03 06:31
Same here 
```json
  "devDependencies": {
    "@rollup/plugin-typescript": "^8.2.5",
    "rollup": "^2.56.3",
    "tslib": "^2.3.1",
    "typescript": "^4.4.2"
  },
```

node version: 14.17.3

**Comment by shellscape** [comment] 2021-09-03 11:48
Duplicate of #983, and you provided no reproduction. Please search issues before opening new ones.

**Closed by shellscape** 2021-09-03 11:48 UTC
