### ISSUE TITLE
@rollup/* plugins has reference @types/estree@0.0.39 it will breaks @types/eslint.

### ISSUE THREAD

**Issue by tianyingchun** [rollup/plugins#665] opened 2020-11-30 10:09 UTC
For all @rollup/* plugins has an issue that referenced `@rollup/pluginutils@^3.1.0` it dep on @types/estree@0.0.39

it will throw below errors:
```
../../node_modules/@types/eslint/index.d.ts(260,41): error TS2724: '"/Users/tianyingchun/Documents/flatjs/flat-toolkit/node_modules/@types/estree/index"' has no exported member named 'ChainExpression'. Did you mean 'ThisExpression'?
../../node_modules/@types/eslint/index.d.ts(283,42): error TS2694: Namespace '"/Users/tianyingchun/Documents/flatjs/flat-toolkit/node_modules/@types/estree/index"' has no exported member 'ImportExpression'.
```
I think all rollup plguin should be upgrade `@rollup/pluginutils` from `3.1.0` to `4.1.0` this issue can be resolved. and `@types/estree^0.0.45`

**Comment by TrySound** [comment] 2020-11-30 11:22
Duplicate of https://github.com/rollup/plugins/issues/640

**Closed by TrySound** 2020-11-30 11:22 UTC
