### ISSUE TITLE
Resolve breaks certain css files

### ISSUE THREAD

**Issue by dkumor** [rollup/plugins#67] opened 2019-08-28 03:07 UTC
This looks like an issue with the interaction of resolve and postcss. Certain imported css files are included without an issue, but others disappear without a trace. Note that this happens *only* when using resolve (see details), so I have submitted it here. I hope that this is the right place for it!

The issue appears when trying to import vuetify's css with resolve and postcss.

- Node-Resolve Plugin Version: `5.2.0`
- Rollup Version: `1.20.2`
- Operating System (or Browser): `archlinux`
- Node Version: `12.9.1`

### How Do We Reproduce?

When trying to import vuetify css with resolve, it simply is not included, as if the import didn't exist
```js
// test.js
import 'vuetify/dist/vuetify.css';
```

```bash
npm i rollup rollup-plugin-node-resolve rollup-plugin-postcss vuetify codemirror
```

```js
// rollup.config.js
import resolve from "rollup-plugin-node-resolve"
import postcss from "rollup-plugin-postcss"

export default {
  input: "test.js",
  output: {
    file: "test.mjs",
    format: "es"
  },
  plugins: [resolve(),postcss()]
}
```

Running rollup with `rollup -c`

### Expected Behavior

Importing certain files with resolve works fine
```js
// test.js
import 'codemirror/lib/codemirror.css';
```

Importing the problematic file directly (without resolve) also works without issue
```bash
cp node_modules/vuetify/dist/vuetify.css ./vuetify.css
```
```js
// test.js
import "./vuetify.css"
```

Trying to import a file that does not exist gives the expected error
```js
import "doesnotexist.css"; // as expected, fails with "Unresolved dependencies" error
```

### Actual Behavior

```js
// test.js
import 'vuetify/dist/vuetify.css';
```
An empty bundle is generated, without any error.

**Comment by shellscape** [comment] 2020-01-09 00:42
@hiendv @dkumor I've finally got the bandwidth to take a look at this. Can either of you break this down into a minimal reproduction using a repo or the [repl](https://repl.it/@rollup/rollup-plugin-repro)? If possible, without using the postcss plugin.

**Comment by dkumor** [comment] 2020-01-09 18:22
While I haven't looked into why the issue is happening, so I'm not sure how to reproduce without postcss, I have recreated the minimal reproduction above (*with* postcss): https://repl.it/repls/EcstaticFaithfulPolygon 

As mentioned above, the issue is not present in 5.0.3.

**Comment by hiendv** [comment] 2020-01-10 04:23
@dkumor's problem is caused by the vuetify `sideEffects` [setting](https://github.com/vuetifyjs/vuetify/blob/7ea1274a71bbd62f99a5ea609f31dd530f707dc8/packages/vuetify/package.json#L40).
- **vuetify** *intends* to mark sideEffects for `node_modules/vuetify/**/*.css`
- **@rollup/plugin-node-resolve** reads it as `node_modules/vuetify/*.css`
- The actual file is located at `node_modules/vuetify/dist/vuetify.css`

You can try modifying `node_modules/vuetify/package.json` sideEffects to `*/*.css` and see if it works.

Mine is another problem with lerna symlink and stuff. I'm trying to reproduce asap.

**Comment by dkumor** [comment] 2020-02-24 17:34
@hiendv yes, looks like that was the issue! If I understand correctly, this means there are two bugs here:
- vuetify has incorrect `sideEffects` setting for css files, which needs to be fixed on their end.
- plugin-replace silently fails when a file is loaded that is not in sideEffects, without giving any indication that something went wrong. I'm not sure *why* the file needs to be in sideEffects to be resolved when explicitly referenced, but if this is intentional, would be nice to get an error message.

Is my understanding correct?

**Comment by hiendv** [comment] 2020-02-25 03:04
@dkumor 
- Not really vuetify problem because the translation of `sideEffects` vary between rollup and webpack. It works fine when bundling with webpack I believe.
- I don't have any idea about plugin-replace but I find it understandable to mark css files as "side-effects" so the tree-shaking works correctly.

**Comment by dkumor** [comment] 2020-02-25 07:10
oops, sorry - not plugin-replace, but node-resolve (edited comment to fix)! Thanks for your help in figuring out this problem @hiendv!

In general, I guess my issue can be boiled down to the fact that plugin-node-resolve is unable to import the explicitly referenced css if it is outside of sideEffects - and it does not notify of the error. The current behavior of silently failing caused me quite a bit of confusion!

**Comment by hiendv** [comment] 2020-02-25 07:37
@dkumor I guess you should keep this issue open because of the difference between rollup and webpack on resolving "*.css* :D

**Comment by shellscape** [comment] 2020-05-02 21:51
Hey folks, this one has gone quite stale. We're going to close for housekeeping but we'd happily review any PRs that pop up to resolve this issue.

**Closed by shellscape** 2020-05-02 21:51 UTC
Labels: s⁵ 💧💧 inconvenient, t³ ✨ enhancement, 🔌 plugin-node-resolve

**Comment by mjsgreen01** [comment] 2020-06-29 19:06
I had a similar issue with `@rollup/plugin-node-resolve` where my nested CSS files were not being included in the output bundle.

Fixed by changing my package.json's `sideEffects` field to `"sideEffects": [
        "**/*.css",
        "**/*.scss"
    ],`

**Comment by mjangir** [comment] 2021-07-29 13:44
> @shellscape The bug remains when setting up the project with lerna.



> @dkumor's problem is caused by the vuetify `sideEffects` [setting](https://github.com/vuetifyjs/vuetify/blob/7ea1274a71bbd62f99a5ea609f31dd530f707dc8/packages/vuetify/package.json#L40).
> 
> * **vuetify** _intends_ to mark sideEffects for `node_modules/vuetify/**/*.css`
> * **@rollup/plugin-node-resolve** reads it as `node_modules/vuetify/*.css`
> * The actual file is located at `node_modules/vuetify/dist/vuetify.css`
> 
> You can try modifying `node_modules/vuetify/package.json` sideEffects to `*/*.css` and see if it works.
> 
> Mine is another problem with lerna symlink and stuff. I'm trying to reproduce asap.

I've the same problem with lerna. Did you find a solution for that? Thanks.
