### ISSUE TITLE
[@rollup/plugin-typescript] declaration files are not generated

### ISSUE THREAD

**Issue by TroyTae** [rollup/plugins#1112] opened 2022-02-19 12:27 UTC
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: "8.3.0"
- Rollup Version: "2.67.3"
- Operating System (or Browser): MacOS Monterey 12.2.1
- Node Version: 17.0.1
- Link to reproduction _(⚠️ read below)_: https://github.com/TroyTae/noliter/tree/ts-test

### Expected Behavior

Declaration files are generated.

### Actual Behavior

Js files are generated well but declaration files are not generated.
<img width="129" alt="image" src="https://user-images.githubusercontent.com/20078201/154800696-823cba0a-72c3-4e59-a584-46292c4b2ff2.png">
And there's no error log.

### Additional Information

I followed this configuration written in README.md:
<img width="272" alt="image" src="https://user-images.githubusercontent.com/20078201/154800514-1dd592d6-eb89-47a7-9714-74287d3363fb.png">

**Comment by shellscape** [comment] 2022-02-19 14:20
Thanks for opening an issue. This is a duplicate of #1049. Closing in favor of that issue. Please continue the discussion there.

**Closed by shellscape** 2022-02-19 14:20 UTC

**Comment by TroyTae** [comment] 2022-02-19 14:43
@shellscape 
Thank you for your answer but is it same issue?
In my case declaration files are not generated.
On the other hand that issue seems declaration files are generated but directory is wrong.

**Comment by shellscape** [comment] 2022-02-19 14:46
Yes, it is. Read that thread and then look at your config; `declarationDir: "."`

**Comment by TroyTae** [comment] 2022-02-19 14:54
@shellscape 
Oh `.` is then excluded.
Thank you for your kindness :)

**Comment by khusamov** [comment] 2022-04-02 11:50
@TroyTae How did you solve your problem? You can look at your `tsconfig.json` ?

**Comment by khusamov** [comment] 2022-04-02 11:56
It turns out that it was necessary to specify the path to the configuration file! Without this, declarations are not generated!

```
typescript({tsconfig: './tsconfig.json'}),
```

Why couldn't this be written into the typescript plugin documentation?

**Comment by shellscape** [comment] 2022-04-02 11:58
> Why couldn't this be written into the typescript plugin documentation?

It definitely could. Please open a PR to add it.
