### ISSUE TITLE
Typescript: Plugin should never crash the process when in watch mode

### ISSUE THREAD

**Issue by JacksonKearl** [rollup/plugins#442] opened 2020-06-08 06:25 UTC
- Rollup Plugin Name: `@rollup/plugin-typescript@4.1.2`
- Rollup Plugin Version: 2.10.5

Currently, when in watch mode and a file being rolled up has syntactical error, for instance:
```ts
await new Promise((resolve) => setTimeout(resolve, 100)) btn.click()
```

the entire process crashes and the watch is terminated. I don't think this should happen, it should instead watch for updates to the file and continue building when the file can be processed.

**Comment by shellscape** [comment] 2020-06-08 11:09
Our issue templates don't contain optional sections or fields. Closing due to removed sections and lack of required reproduction.

**Closed by shellscape** 2020-06-08 11:09 UTC
