### ISSUE TITLE
@rollup/plugin-replace failing since 2.4.0

### ISSUE THREAD

**Issue by diego-antonelli** [rollup/plugins#812] opened 2021-02-22 13:01 UTC
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: 2.4.0
- Rollup Version: 2.39.0
- Operating System (or Browser): Windows & Linux
- Node Version: 14
- Link to reproduction _(⚠️ read below)_: https://github.com/mendix/widgets-resources/pull/469/checks?check_run_id=1952183540

### Expected Behavior
Pass builds without throw error

### Actual Behavior
Throwing the following error: Error: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to true, as the next major version will default this option to true.

Even adding preventAssignment it throws the error and rollup aborts the builds.

### Additional Information
It is happening since the last update 12h ago

**Comment by shellscape** [comment] 2021-02-22 13:21
@diego-antonelli we closed your previous issue because you disregarded the information about requiring a valid reproduction. Creating a duplicate issue doesn't make the invalid reproduction any more valid. Please do not create further duplicates, and please do not create additional issues that disregard our templates. 

Closing as duplicate of #811 and for lacking a valid reproduction.

**Closed by shellscape** 2021-02-22 13:21 UTC

**Comment by diego-antonelli** [comment] 2021-02-22 13:45
@shellscape I added a link with a valid case at least was showing the error. Also @danielroe mentioned this issue in his PR, but now the issue is closed.

**Comment by shellscape** [comment] 2021-02-22 13:48
Our issue templates _thoroughly_ explain what options for valid reproductions are. What you feel is valid for triage is not necessarily what maintainers here need. Please respect their hard work and the time they give freely to make your work easier, by taking a few extra moments from your day to follow the guidelines in our issue templates.
