### ISSUE TITLE
[typescript] tslib helpers are undefined

### ISSUE THREAD

**Issue by philipahlberg** [rollup/plugins#484] opened 2020-07-03 19:38 UTC
TypeScript is using `tslib` helpers when necessary, but no imports or definitions are generated.

- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: 5.0.1
- Rollup Version: 2.18.2
- Operating System (or Browser): [repl.it](https://repl.it), also Windows 10
- Node Version: v12.16.3 (repl.it) and v14.5.0 (local)

### How Do We Reproduce?

https://repl.it/repls/VapidAptScript

### Expected Behavior

The `tslib` helper function `__classPrivateFieldSet` should be defined, either as a local definition or through an import statement.

### Actual Behavior

`__classPrivateFieldSet` is undefined.

**Comment by DominicTobias** [comment] 2020-07-14 14:22
Similar issue - `__extends` is undefined. No helpers are being built in.

```json
{
  "compilerOptions": {
    "jsx": "react",
    "outDir": "./dist",
    "declaration": true,
    "module": "ES6",
    "target": "es5",
    "rootDir": "./src", // neeeded to fix a compilation error
    "importHelpers": true // no change
  },
  "include": ["./src"]
}
```

**Comment by philipahlberg** [comment] 2020-07-23 11:30
For what it's worth, building with `tsc` directly (bypassing rollup) correctly defines the helper function in the output.

**Comment by Inori-Lover** [comment] 2020-09-27 05:28
> Similar issue - `__extends` is undefined. No helpers are being built in.
> 
> ```json
> {
>   "compilerOptions": {
>     "jsx": "react",
>     "outDir": "./dist",
>     "declaration": true,
>     "module": "ES6",
>     "rootDir": "./src", // neeeded to fix a compilation error
>     "importHelpers": true // no change
>   },
>   "include": ["./src"]
> }
> ```

how to reproduce this?
https://repl.it/repls/ThirdFoolhardyTechnology
i want to reduce package size but it always emit `__awaiter`.

**Comment by Inori-Lover** [comment] 2020-09-27 05:36
> > Similar issue - `__extends` is undefined. No helpers are being built in.
> > ```json
> > {
> >   "compilerOptions": {
> >     "jsx": "react",
> >     "outDir": "./dist",
> >     "declaration": true,
> >     "module": "ES6",
> >     "rootDir": "./src", // neeeded to fix a compilation error
> >     "importHelpers": true // no change
> >   },
> >   "include": ["./src"]
> > }
> > ```
> 
> how to reproduce this?
> https://repl.it/repls/ThirdFoolhardyTechnology
> i want to reduce package size but it always emit `__awaiter`.

and i found it:
https://github.com/rollup/plugins/commit/262cf3d05cef6d86c1892663cb82fbf9ab1f461e#diff-d0e8f6b9abc1fa17aec795d056823ae0R25-R27

why?

**Comment by NotWoods** [comment] 2020-09-27 05:51
We force useTslib because helpers will otherwise be put inline, resulting in duplicate helpers in each source module.

**Comment by NotWoods** [comment] 2020-09-27 05:54
Also, to avoid using `__awaiter`, you need to change the `"target"` to a version that support async functions like `"es2018"`.

**Comment by Inori-Lover** [comment] 2020-09-29 03:41
> Also, to avoid using `__awaiter`, you need to change the `"target"` to a version that support async functions like `"es2018"`.

```
{
  "compilerOptions": {
    "target": "ES5",
   
    "importHelpers": false,
    "noEmitHelpers": true
  }
}
```

when you set like this, the output code will use global `__awaiter` var instanceof inline the source. that is what i want

[online demo](https://www.typescriptlang.org/play?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&noEmitHelpers=true&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=1#code/IYZwngdgxgBAZgV2gFwJYHsIwIIwBQCUMA3gL4BQ5ApgB4AO6ATsjACZVzAIA2LoksRCgxYAQviLFyMGTGAB3YKhajC5UkA)

**Comment by ArrayKnight** [comment] 2020-10-21 19:22
Running into the same issue, tslib isn't being included automatically as intended.

```Uncaught ReferenceError: __spreadArrays is not defined```

**Comment by ArrayKnight** [comment] 2020-10-23 18:52
I noticed that when I switched the `output` `format` in the `rollup.config.js` from 'es' to 'iife', the issue was resolved and all tslib helpers were included.

**Comment by limitlessloop** [comment] 2021-03-09 12:34
The typescript docs says that `"noEmitHelpers":` is disabled by default, ie it should emit helpers by default. Is this something that `@rollup/plugin-typescript` should mirror? `rollup-plugin-typescript` is configured with this by default for anyone who's struggling to get it working.

**Comment by shellscape** [comment] 2021-07-29 17:21
Closing given that this issue is more than a year old and without community contribution for a fix, and considering the reasoning for why the plugin works like it does, plus various workarounds. If anyone would like to open a PR with a proposal to fix all or some of the use cases mentioned in the comments for this issue, we'd be happy to take a look.

**Closed by shellscape** 2021-07-29 17:21 UTC
Labels: c³ ⋅ PR welcome, t¹ 🐞 bug, 🔌 plugin-typescript
