### ISSUE TITLE
plugin-alias: Resolve isn't applied on all imports

### ISSUE THREAD

**Issue by gawlk** [rollup/plugins#37] opened 2019-11-17 14:38 UTC
Hi !

So, I can't figure out if it's a normal behavior or not but like I said in the title, not all paths are  resolved by the `@rollup/plugin-alias` extension.

- Rollup Plugin Name: alias
- Rollup Plugin Version: 2.2.0
- Rollup Version: 1.27.0
- Operating System (or Browser): Mac OS Catalina, Firefox 70
- Node Version: 13.1

### How Do We Reproduce?

Here's an example:

My configuration of the `alias` plugin in `rollup.config.js`:
```js
...
alias({
    entries: {
        'src': `${__dirname}/src`
    },
    resolve: [
        '.js',
        '.svelte',
        '/index.js',
        '/index.svelte',
        ''
    ],
}),
...
```

We imagine that there is a `svelte` component called `Button.svelte` in `src/components`.

So this works:

`src/pages/Home.svelte`:
```js
...
import Button from 'src/components/Button';
...
```

**Please note that here the component is imported via the alias `src` created before in the plugin configuration.**

[Source code](https://github.com/gawlk/svind)

### Expected Behavior

So I expect this to work (`src/pages/Home.svelte`):
```js
...
import Button from '../components/Button';
...
```

### Actual Behavior

Yet, it doesn't.

The error will be:
```
[!] Error: Could not resolve '../components/Button' from src/pages/Home.svelte
Error: Could not resolve '../components/Button' from src/pages/Home.svelte
    at error (/Users/k/Documents/Code/Svelte/svind/node_modules/rollup/dist/rollup.js
:5351:30)
    at ModuleLoader.handleMissingImports (/Users/k/Documents/Code/Svelte/svind/node_m
odules/rollup/dist/rollup.js:12192:17)
    at ModuleLoader.<anonymous> (/Users/k/Documents/Code/Svelte/svind/node_modules/ro
llup/dist/rollup.js:12083:30)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/k/Documents/Code/Svelte/svind/node_modules/rollup/dist/rollu
p.js:41:28)
```

So I'm forced to do:

`src/pages/Home.svelte`:
```js
...
import Button from '../components/Button.svelte';
...
```

And it doesn't seem logical to me.

I don't know if I have to add I rule to the alias function in `rollup.config.js` or not ? I tried everything and if it cannot work, I think that it would be a nice feature to have, especially when you have components that have components.

**Comment by shellscape** [comment] 2019-11-17 14:51
Hey @gawlk, thanks for opening an issue. Normally we'd nuke your issue because it contains a number of problems, but since it looks like you might be new to Github, I'd like to outline what's wrong so that you'll have success moving forward:

- Issue templates on Github aren't generally considered optional
- Maintainers take great care in putting templates together to not only help users more efficiently, but also to make the very time-intensive task of supporting users and the project more efficient
- Skipping issue templates or template sections isn't good, but ignoring templates altogether is worse
- The issue template descriptions often contain important info. e.g.

> 👉🏽 Need help or tech support? Please don't open an issue! Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs.

- The issue templates themselves often contain important info. e.g. from the Bug Report template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>  1. Using the REPL at https://rollupjs.org/repl/, or
>  2. Work to isolate the problem and provide the exact steps in this issue, or
>  3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     These may take more time to triage than the other options.

Since you don't seem to be reporting a bug, but rather asking for support on how to use the plugin, this issue should probably be closed, and you should try one of the support options. If you meant to report a bug, then you should follow the instructions to provide a minimal reproduction.

**Comment by gawlk** [comment] 2019-11-17 15:24
Well, I'm not sure if this is a bug or not but thank you for keeping my issue.

There is not much to add to the `How Do We Reproduce?` part. My whole problem is that the plugin doesn't resolve the paths that aren't being processed in the `entries`.

In a nutshell, it doesn't automatically add the extension to relative paths.

**Comment by shellscape** [comment] 2019-11-17 15:36
I believe you missed some important parts of my reply there. If you're unable to put together a proper reproduction, we'll have to close this one.

**Comment by gawlk** [comment] 2019-11-17 15:51
Here's a simple repository: https://github.com/gawlk/svind

Like I said I don't do anything complex or weird, I'm just asking if this is a normal behavior

**Comment by shellscape** [comment] 2019-11-17 16:03
I'm sorry, but I'm going to have to close this issue. I've tried several times to guide you in the right direction. While the repo link is appreciated, it's nowhere near a minimal reproduction as linked to above, and mentioned several times. If you'd still like to report this as a potential bug, please create a new issue go through the proper template (Bug Report), fill it out in its entirety, read the instructions for providing a **_minimal reproduction_**, and resubmit the issue.

**Closed by shellscape** 2019-11-17 16:03 UTC
Labels: c⁵ ⋅ question, x⁶ ⋅ invalid, 💩 template removed, 🔌 plugin/alias
