### ISSUE TITLE
Used `@rollup/plugin-commonjs` but also get `require` synax.

### ISSUE THREAD

**Issue by underfin** [rollup/plugins#554] opened 2020-08-25 09:11 UTC
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 15.0.0
- Rollup Version: 2.26.5
- Operating System (or Browser): Mac OS
- Node Version: 12.14.0
- Link to reproduction _(⚠️ read below)_:
https://github.com/underfin/rollup-cjs-to-es-issues

1. clone repo
2.run `npm run build` and see `output.js` https://github.com/underfin/rollup-cjs-to-es-issues/blob/master/output.js#L2399.

### Expected Behavior

Output code should be a correct es module.

### Actual Behavior

Used `@rollup/plugin-commonjs` but also get `require` synax.

### Additional Information

I debug for this and found the code is already transformed into es module(I debuged with here https://github.com/rollup/plugins/blob/master/packages/commonjs/src/index.js#L208), but output is also cjs version.I don't what happend with this..

The original issues is here https://github.com/vitejs/vite/issues/728#issuecomment-677649726.

**Comment by lukastaegert** [comment] 2020-08-25 11:31
I had a look and the solution is simple: `rollup-plugin-node-globals` MUST be placed AFTER `@rollup/plugin-commonjs`. The reason is that this plugin injects import statements that will confuse the CommonJS detection of the commonjs plugin. Another option would be to add `transformMixedModules: true` to the Commonjs plugin. There is not much more it seems we can do here except possibly add this case to the documentation. More importantly, I think this restriction should be added to the documentation of rollup-plugin-node-globals, though.

**Comment by underfin** [comment] 2020-08-26 02:32
@lukastaegert Thanks! I have a try with this. It can works with build for now. 

But I get other error with runtime.I updated the repo, you can take a look.
For detail, it is code inside output.
```
var bufferEs6 = /*#__PURE__*/Object.freeze({
	__proto__: null, 
	INSPECT_MAX_BYTES: INSPECT_MAX_BYTES,
	kMaxLength: _kMaxLength,
	Buffer: Buffer,
	SlowBuffer: SlowBuffer,
	isBuffer: isBuffer
});
// ... many code 

for (key$3 in bufferEs6) {
  if (!bufferEs6.hasOwnProperty(key$3)) continue // this will thorw error, because the transformed code add `__proto__: null`
  if (key$3 === 'SlowBuffer' || key$3 === 'Buffer') continue
  safer[key$3] = bufferEs6[key$3];
}

```

**Comment by shellscape** [comment] 2020-09-06 16:26
@underfin you'll have to inspect what the value of bufferEs6 is and why it doesn't have that property. If you track that down to a problem with a rollup plugin that exists in this repo, please do open a new issue. My guess is that it's a problem with `rollup-plugin-node-globals`. Since the original issue reported is resolved, we're going to close this one.

**Closed by shellscape** 2020-09-06 16:26 UTC

**Comment by lukastaegert** [comment] 2020-09-06 18:49
Actually the problem is that Rollup creates proper ES namespaces that do not have `Object` as prototype. Therefore `hasOwnProperty` does not exist. While they should just not use `hasOwnProperty` on a namespace in an ideal world, the best and simplest solution I could think of would be a flag in Rollup core to prevent removing the object prototype. @underfin could you open an issue in in the main Rollup repo so that we do not forget to add such a flag? I think it could also help to solve other such issues.

**Comment by underfin** [comment] 2020-09-07 01:59
@lukastaegert I open a new issue is here https://github.com/rollup/rollup/issues/3765
