### ISSUE TITLE
@rollup/plugin-replace now crashes error explanation not good enough

### ISSUE THREAD

**Issue by OlagStegan** [rollup/plugins#815] opened 2021-02-22 17:10 UTC
the Node error during build:

Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.

no indication in documentation where to add this config is this new config worked fine yesterday no error now cannot get rid of!

tried latest version and no resolution. please indicate where to add this parameter (in the documentation would be nice)

- Rollup Plugin Name: 
- Rollup Plugin Version:
- Rollup Version:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_:

**Comment by shellscape** [comment] 2021-02-22 17:35
If you'd like a project to help you with a problem, please respect what the project asks of you. You didn't fill out our template, provide a reproduction, and it appears you didn't search the issues or PRs here for your answer before opening this issue to vent. Closing as duplicate of #811.

**Closed by shellscape** 2021-02-22 17:35 UTC

**Comment by OlagStegan** [comment] 2021-02-23 17:15
Just shoot the messenger. :(

Sorry not familiar with process here

I have "inherited" a project that uses "rollup" that worked fine until I performed a standard 
yarn update-interactive
now I get the message on yarn build

I came to the Git page from the package.json file there was no information in the README to indicate where to plce the config property 'preventAssignment'

probably bread & butter to experienced rollup users (not me) the rollup.config.js is quite complex with multiple plugins.

If a duplicate of an earlier post once again I'm sorry but a link to a previous answer would be more helpful as searching gave nothing.  The README is still missing the vital information anyway!

I see no template. 

Thank you
Olag

**Comment by shellscape** [comment] 2021-02-23 17:50
> Sorry not familiar with process here
> I see no template.

There is no process other than filling out the template. The template is what you wrote above, the bit that you ignored directly below what you wrote. You'd have to willfully ignore everything you see in order to claim that you didn't see a template. You chose the "Bug" issue type on this page https://github.com/rollup/plugins/issues/new/choose, instead of the "Documentation" issue type. We know that because the template for the "Bug" issue is what you left below what you typed. You would have had to ignore the following two warnings in the template as well:

>   🚨 Your issue will be CLOSED if:
>     - This template is removed
>     - Parts of this template are removed

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!

I'm responding with all of this information because I'm assuming that your experience with Github is not deep, or that Github is not familiar. However, I would bet that you're more than capable of reading what was below what you typed. Issue templates have been a core part of Github projects for many years now, and you're likely to run into more friction if you routinely disregard them on other projects https://docs.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests
